language: perl

sudo: false

# remember need at least one install command, even if there are no
# prereqs, else travis will try to install deps using cpanm
# which is not what we want since this is a Dist::Zilla dist.
install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - dzil test -v

env:
  global:
    - PERL_USE_UNSAFE_INC=0
